### ISSUE TITLE
Compiling under Mac OS 13.2 fatal error: 'bfd.h' file not found

### ISSUE THREAD

**Issue by micpro7** [th0u/sbsigntools-macOS#1]
I am having issues compiling under Mac OS Ventura 13.2 

 autoreconf -I 
  ./configure --prefix=/usr ac_cv_header_bfd_h=yes endian=little little_endian=1 big_endian=0 CRTPATH=./ext
  
completes no error

however running make results in

sbsigntools-macOS-main % make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in lib/ccan
make[2]: Nothing to be done for `all'.
Making all in src
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra --std=gnu99  -Wno-gnu-variable-sized-type-not-at-end -I../lib/ccan/ -I/opt/local/include -I../ext/ -Werror -g -O2 -MT sbsign-sbsign.o -MD -MP -MF .deps/sbsign-sbsign.Tpo -c -o sbsign-sbsign.o `test -f 'sbsign.c' || echo './'`sbsign.c
In file included from sbsign.c:57:
In file included from ./idc.h:35:
./image.h:37:10: fatal error: 'bfd.h' file not found
#include <bfd.h>
         ^~~~~~~
1 error generated.
make[2]: *** [sbsign-sbsign.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

any help or precompiled binaries for Mac OS 13.2 would be appreciated

**Comment by th0u** [comment]
On my system, bfd.h and other files reside in "/opt/local/include" and was provided by binutils, which I installed using MacPorts.

**Comment by micpro7** [comment]
I fixed my issues by installing binutils and openssl11

Thanks
